apiVersion: kfg.dev/v1alpha1
kind: Converter
metadata:
  name: kfg.convert.self.mcp.opencode
spec:
  input:
    format: yaml
  engine:
    expression: |
      (.name) as $n | {($n): {"command": .server.command, "args": .server.args, "env": .server.env}}
  output:
    format: json
