apiVersion: kfg.dev/v1alpha1
kind: Cmd
metadata:
  name: kfg.agent.cmd.opencode
  commandName: opencode
spec:
  run: |
    command opencode "$@"
  env:
    AGENT: "opencode"
---
apiVersion: kfg.dev/v1alpha1
kind: Cmd
metadata:
  name: kfg.agent.cmd.gemini
  commandName: gemini
spec:
  run: |
    command gemini "$@"
  env:
    AGENT: "gemini"
---
apiVersion: kfg.dev/v1alpha1
kind: Cmd
metadata:
  name: kfg.agent.cmd.pi
  commandName: pi
spec:
  run: |
    command pi "$@"
  env:
    AGENT: "pi"
---
apiVersion: kfg.dev/v1alpha1
kind: Cmd
metadata:
  name: kfg.agent.cmd.claude
  commandName: claude
spec:
  run: |
    command claude "$@"
  env:
    AGENT: "claude"
