apiVersion: kfg.dev/v1alpha1
kind: Cmd
metadata:
  name: kfg.agent.cmd.openspec
  commandName: openspec
spec:
  run: |
    _kfg.log.debug "openspec:cmd" "$@"
    command openspec "$@"
  env:
    AGENT: "openspec"
