apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agents
  - cmds
  - steps
  - prompts
  - subagents
  - converters
  - chrome-devtools
  - ctx7
  - gws
  - notebooklm
  - openspec
  - playwright