# nixai shell integration
# set: dev
# shell: bash
# Generated by nixai shell compiler

# Internal context management

__nixai_ctx_reset() {
    declare -gA __nixai_outputs=()
}

__nixai_output_set() {
    local step="$1"
    local name="$2"
    local value="$3"
    __nixai_outputs["${step}.${name}"]="$value"
}

__nixai_output_get() {
    local step="$1"
    local name="$2"
    printf '%s' "${__nixai_outputs["${step}.${name}"]:-}"
}

# When condition evaluation

__nixai_when_equals() {
    local step="$1"
    local name="$2"
    local expected="$3"
    local actual="$(__nixai_output_get "$step" "$name")"
    [ "$actual" = "$expected" ]
}

__nixai_when_in() {
    local step="$1"
    local name="$2"
    local actual="$(__nixai_output_get "$step" "$name")"
    shift 2
    for expected in "$@"; do
        [ "$actual" = "$expected" ] && return 0
    done
    return 1
}

__nixai_when_contains() {
    local step="$1"
    local name="$2"
    local substring="$3"
    local actual="$(__nixai_output_get "$step" "$name")"
    [ -z "$actual" ] && return 1
    [[ "$actual" == *"$substring"* ]]
}

__nixai_when_matches() {
    local step="$1"
    local name="$2"
    local pattern="$3"
    local actual="$(__nixai_output_get "$step" "$name")"
    [ -z "$actual" ] && return 1
    [[ "$actual" =~ $pattern ]]
}

__nixai_when_allof() {
    for cond in "$@"; do
        eval "$cond" || return 1
    done
    return 0
}

__nixai_when_anyof() {
    for cond in "$@"; do
        eval "$cond" && return 0
    done
    return 1
}

__nixai_when_not() {
    local cond="$1"
    eval "$cond" && return 1
    return 0
}

# Step execution functions

__nixai_run_step_check-env() {
    # Execute
    test -f .env || return $?
}

__nixai_run_step_init-project() {
    # Execute
    npm init -y || return $?
}

# Command wrappers

init() {
    local __nixai_status=0

    # Reset context
    __nixai_ctx_reset

    # Before steps
    __nixai_run_step_check-env || return $?

    # Main body
    echo "Initializing project"
    __nixai_status=$?

    # After steps
    [ $__nixai_status -eq 0 ] && __nixai_run_step_init-project

    return $__nixai_status
}