# kfg shell integration
# set: dev
# shell: bash
# Generated by kfg shell compiler

# Internal context management

__kfg_ctx_reset() {
    declare -gA __kfg_outputs=()
}

__kfg_output_set() {
    local step="$1"
    local name="$2"
    local value="$3"
    __kfg_outputs["${step}.${name}"]="$value"
}

__kfg_output_get() {
    local step="$1"
    local name="$2"
    printf '%s' "${__kfg_outputs["${step}.${name}"]:-}"
}

# When condition evaluation

__kfg_when_equals() {
    local step="$1"
    local name="$2"
    local expected="$3"
    local actual="$(__kfg_output_get "$step" "$name")"
    [ "$actual" = "$expected" ]
}

__kfg_when_in() {
    local step="$1"
    local name="$2"
    local actual="$(__kfg_output_get "$step" "$name")"
    shift 2
    for expected in "$@"; do
        [ "$actual" = "$expected" ] && return 0
    done
    return 1
}

__kfg_when_contains() {
    local step="$1"
    local name="$2"
    local substring="$3"
    local actual="$(__kfg_output_get "$step" "$name")"
    [ -z "$actual" ] && return 1
    [[ "$actual" == *"$substring"* ]]
}

__kfg_when_matches() {
    local step="$1"
    local name="$2"
    local pattern="$3"
    local actual="$(__kfg_output_get "$step" "$name")"
    [ -z "$actual" ] && return 1
    [[ "$actual" =~ $pattern ]]
}

__kfg_when_allof() {
    for cond in "$@"; do
        eval "$cond" || return 1
    done
    return 0
}

__kfg_when_anyof() {
    for cond in "$@"; do
        eval "$cond" && return 0
    done
    return 1
}

__kfg_when_not() {
    local cond="$1"
    eval "$cond" && return 1
    return 0
}

# Step execution functions

__kfg_run_step_check-env() {
    # Execute
    test -f .env || return $?
}

__kfg_run_step_init-project() {
    # Execute
    npm init -y || return $?
}

# Command wrappers

init() {
    local __kfg_status=0

    # Reset context
    __kfg_ctx_reset

    # Before steps
    __kfg_run_step_check-env || return $?

    # Main body
    echo "Initializing project"
    __kfg_status=$?

    # After steps
    [ $__kfg_status -eq 0 ] && __kfg_run_step_init-project

    return $__kfg_status
}