apiVersion: kfg.dev/v1alpha1
kind: Assets
metadata:
  name: ai.claude.asset.settings
spec:
  input:
    format: yaml
  data:
    permissions:
      allow:
        - "Read(/{env:HOME}/Downloads/**)"
        - "Read(/**)"
        - "Edit(/**)"
        - "Bash(/**)"
      deny: []
