apiVersion: kfg.dev/v1alpha1
kind: Converter
metadata:
  name: ai.claude.conv.mcp
spec:
  input:
    format: yaml
  engine:
    expression: |
      (.name) as $n | {($n): {"command": .server.command, "args": .server.args}}
  output:
    format: json
