package templates

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// GoldenTest tests compare generated output with expected golden files
// to ensure template output is deterministic and correct.

func TestGoldenHeader(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := HeaderData{
		SetName: "dev",
		Shell:   "bash",
	}

	output, err := tm.ExecuteHeader(data)
	assert.NoError(t, err)

	// Expected header should contain these lines
	expectedLines := []string{
		"# kfg shell integration",
		"# set: dev",
		"# shell: bash",
		"# Generated by kfg shell compiler",
	}

	for _, line := range expectedLines {
		assert.Contains(t, output, line, "header should contain expected line")
	}
}

func TestGoldenHelpers(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	output, err := tm.ExecuteHelper()
	assert.NoError(t, err)

	// Helpers should define these functions
	expectedFunctions := []string{
		"__kfg_ctx_reset()",
		"__kfg_output_set()",
		"__kfg_output_get()",
		"__kfg_when_equals()",
		"__kfg_when_in()",
		"__kfg_when_contains()",
		"__kfg_when_matches()",
		"__kfg_when_allof()",
		"__kfg_when_anyof()",
		"__kfg_when_not()",
		"_kfg.log.error()",
		"_kfg.log.warn()",
		"_kfg.log.info()",
		"_kfg.log.detail()",
		"_kfg.log.debug()",
	}

	for _, fn := range expectedFunctions {
		assert.Contains(t, output, fn, "helpers should define function %s", fn)
	}
}

func TestGoldenStepSimple(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:  "simple-step",
		RunScript: "echo hello world",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Expected structure
	expectedContent := []string{
		"__kfg_run_step_simple-step()",
		"# Execute",
		"echo hello world",
		"|| return $?",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "step output should contain: %s", content)
	}

	// Should NOT have when condition
	assert.NotContains(t, output, "if !", "simple step should not have when condition")
	assert.NotContains(t, output, "Skipped", "simple step should not have skip logic")
}

func TestGoldenStepWithOutput(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:   "output-step",
		HasOutput:  true,
		RunScript:  "cat config.json",
		OutputName: "config",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Expected output capture structure
	expectedContent := []string{
		"__kfg_run_step_output-step()",
		"# Execute and capture output",
		"local __output",
		"__output=\"$( cat config.json )\"",
		"__kfg_output_set",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "step with output should contain: %s", content)
	}
}

func TestGoldenStepWithWhen(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:      "conditional-step",
		RunScript:     "echo conditional",
		WhenCondition: "__kfg_when_equals \"check\" \"result\" \"ready\"",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Expected when condition structure
	expectedContent := []string{
		"__kfg_run_step_conditional-step()",
		"# When condition",
		"if ! __kfg_when_equals",
		"return 0  # Skipped",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "step with when should contain: %s", content)
	}
}

func TestGoldenStepMultiLine(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:    "multi-step",
		IsMultiLine: true,
		RunLines: []string{
			"echo 'line 1'",
			"echo 'line 2'",
			"echo 'line 3'",
		},
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Expected multi-line structure
	expectedContent := []string{
		"__kfg_run_step_multi-step()",
		"(",
		"echo 'line 1'",
		"echo 'line 2'",
		"echo 'line 3'",
		")",
		"|| return $?",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "multi-line step should contain: %s", content)
	}
}

func TestGoldenCommandSimple(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := CommandData{
		CommandName: "build",
		MainRun:     "npm run build",
	}

	output, err := tm.ExecuteCommand(data)
	assert.NoError(t, err)

	// Expected command wrapper structure
	expectedContent := []string{
		"build()",
		"local __kfg_status=0",
		"# Reset context",
		"__kfg_ctx_reset",
		"# Main body",
		"npm run build",
		"__kfg_status=$?",
		"return $__kfg_status",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "simple command should contain: %s", content)
	}

	// Should NOT have before/after steps sections
	assert.NotContains(t, output, "# Before steps", "simple command should not have before steps")
	assert.NotContains(t, output, "# After steps", "simple command should not have after steps")
}

func TestGoldenCommandWithSteps(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := CommandData{
		CommandName:    "deploy",
		MainRun:        "kubectl apply -f deployment.yaml",
		HasBeforeSteps: true,
		BeforeSteps: []BeforeStepData{
			{StepName: "check-cluster", IgnoreFailure: false},
			{StepName: "build-image", IgnoreFailure: false},
		},
		HasAfterSteps: true,
		AfterSteps: []AfterStepData{
			{StepName: "verify-deployment", IgnoreFailure: false},
			{StepName: "notify-team", IgnoreFailure: true},
		},
	}

	output, err := tm.ExecuteCommand(data)
	assert.NoError(t, err)

	// Expected command with steps structure
	expectedContent := []string{
		"deploy()",
		"# Before steps",
		"__kfg_run_step_check-cluster || return $?",
		"__kfg_run_step_build-image || return $?",
		"kubectl apply -f deployment.yaml",
		"# After steps",
		"[ $__kfg_status -eq 0 ] && __kfg_run_step_verify-deployment",
		"__kfg_run_step_notify-team || true",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "command with steps should contain: %s", content)
	}
}

func TestGoldenDeterministicOutput(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:  "deterministic-test",
		RunScript: "echo test",
	}

	// Execute the same template multiple times
	output1, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	output2, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	output3, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// All outputs should be identical
	assert.Equal(t, output1, output2, "template output should be deterministic")
	assert.Equal(t, output2, output3, "template output should be deterministic")
	assert.Equal(t, output1, output3, "template output should be deterministic")
}

func TestGoldenFullExample(t *testing.T) {
	// This test verifies a complete example combining header, helpers, steps, and commands
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	// Generate header
	headerData := HeaderData{
		SetName: "dev",
		Shell:   "bash",
	}
	header, err := tm.ExecuteHeader(headerData)
	assert.NoError(t, err)

	// Generate helpers
	helpers, err := tm.ExecuteHelper()
	assert.NoError(t, err)

	// Generate a step
	stepData := StepData{
		StepName:  "check-env",
		RunScript: "test -f .env",
	}
	step, err := tm.ExecuteStep(stepData)
	assert.NoError(t, err)

	// Generate a command
	cmdData := CommandData{
		CommandName: "init",
		MainRun:     "echo Initializing",
	}
	cmd, err := tm.ExecuteCommand(cmdData)
	assert.NoError(t, err)

	// Combine all parts
	fullOutput := header + "\n" + helpers + "\n" + step + "\n" + cmd

	// Verify the full output contains all expected sections
	assert.Contains(t, fullOutput, "# kfg shell integration", "full output should have header")
	assert.Contains(t, fullOutput, "__kfg_ctx_reset", "full output should have helpers")
	assert.Contains(t, fullOutput, "__kfg_run_step_check-env", "full output should have step")
	assert.Contains(t, fullOutput, "init()", "full output should have command")
}
