package templates

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// GoldenTest tests compare generated output with expected golden files
// to ensure template output is deterministic and correct.

func TestGoldenHeader(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := HeaderData{
		SetName: "dev",
		Shell:   "bash",
	}

	output, err := tm.ExecuteHeader(data)
	assert.NoError(t, err)

	// Expected header should contain these lines
	expectedLines := []string{
		"# kfg shell integration",
		"# set: dev",
		"# shell: bash",
		"# Generated by kfg shell compiler",
	}

	for _, line := range expectedLines {
		assert.Contains(t, output, line, "header should contain expected line")
	}
}

func TestGoldenHelpers(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	output, err := tm.ExecuteHelper()
	assert.NoError(t, err)

	// Helpers should define these functions
	expectedFunctions := []string{
		"__kfg_ctx_reset()",
		"__kfg_output_set()",
		"__kfg_output_get()",
		"__kfg_when_equals()",
		"__kfg_when_in()",
		"__kfg_when_contains()",
		"__kfg_when_matches()",
		"__kfg_when_allof()",
		"__kfg_when_anyof()",
		"__kfg_when_not()",
		"__kfg_log_error()",
		"__kfg_log_warn()",
		"__kfg_log_info()",
		"__kfg_log_detail()",
		"__kfg_log_debug()",
	}

	for _, fn := range expectedFunctions {
		assert.Contains(t, output, fn, "helpers should define function %s", fn)
	}
}

func TestGoldenStepSimple(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:  "simple-step",
		RunScript: "echo hello world",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Expected structure
	expectedContent := []string{
		"__kfg_run_step_simple-step()",
		"# Execute",
		"echo hello world",
		"|| return $?",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "step output should contain: %s", content)
	}

	// Should NOT have when condition
	assert.NotContains(t, output, "if !", "simple step should not have when condition")
	assert.NotContains(t, output, "Skipped", "simple step should not have skip logic")
}

func TestGoldenStepWithOutput(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:   "output-step",
		HasOutput:  true,
		RunScript:  "cat config.json",
		OutputName: "config",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Expected output capture structure (temp file based, runs in parent shell)
	expectedContent := []string{
		"__kfg_run_step_output-step()",
		"# Execute and capture output via temporary file (runs in parent shell)",
		"local __output_file",
		"__output_file=$(mktemp)",
		"{ cat config.json; } > \"$__output_file\"",
		"__output=$(<\"$__output_file\")",
		"__kfg_output_set",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "step with output should contain: %s", content)
	}

	// Should NOT use command substitution (which runs in subshell)
	assert.NotContains(t, output, "__output=\"$( ", "step with output should NOT use command substitution")
}

func TestGoldenStepWithWhen(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:      "conditional-step",
		RunScript:     "echo conditional",
		WhenCondition: "__kfg_when_equals \"check\" \"result\" \"ready\"",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Expected when condition structure
	expectedContent := []string{
		"__kfg_run_step_conditional-step()",
		"# When condition",
		"if ! __kfg_when_equals",
		"return 0  # Skipped",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "step with when should contain: %s", content)
	}
}

func TestGoldenStepMultiLine(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:    "multi-step",
		IsMultiLine: true,
		RunLines: []string{
			"echo 'line 1'",
			"echo 'line 2'",
			"echo 'line 3'",
		},
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Expected multi-line structure
	expectedContent := []string{
		"__kfg_run_step_multi-step()",
		"(",
		"echo 'line 1'",
		"echo 'line 2'",
		"echo 'line 3'",
		")",
		"|| return $?",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "multi-line step should contain: %s", content)
	}
}

func TestGoldenCommandSimple(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := CommandData{
		CommandName: "build",
		MainRun:     "npm run build",
	}

	output, err := tm.ExecuteCommand(data)
	assert.NoError(t, err)

	// Expected command wrapper structure
	expectedContent := []string{
		"build()",
		"local __kfg_status=0",
		"# Reset context",
		"__kfg_ctx_reset",
		"# Main body",
		"npm run build",
		"__kfg_status=$?",
		"return $__kfg_status",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "simple command should contain: %s", content)
	}

	// Should NOT have before/after steps sections
	assert.NotContains(t, output, "# Before steps", "simple command should not have before steps")
	assert.NotContains(t, output, "# After steps", "simple command should not have after steps")
}

func TestGoldenCommandWithSteps(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := CommandData{
		CommandName:    "deploy",
		MainRun:        "kubectl apply -f deployment.yaml",
		HasBeforeSteps: true,
		BeforeSteps: []BeforeStepData{
			{StepName: "check-cluster", IgnoreFailure: false},
			{StepName: "build-image", IgnoreFailure: false},
		},
		HasAfterSteps: true,
		AfterSteps: []AfterStepData{
			{StepName: "verify-deployment", IgnoreFailure: false},
			{StepName: "notify-team", IgnoreFailure: true},
		},
	}

	output, err := tm.ExecuteCommand(data)
	assert.NoError(t, err)

	// Expected command with steps structure
	expectedContent := []string{
		"deploy()",
		"# Before steps",
		"__kfg_run_step_check-cluster || return $?",
		"__kfg_run_step_build-image || return $?",
		"kubectl apply -f deployment.yaml",
		"# After steps",
		"[ $__kfg_status -eq 0 ] && __kfg_run_step_verify-deployment",
		"__kfg_run_step_notify-team || true",
	}

	for _, content := range expectedContent {
		assert.Contains(t, output, content, "command with steps should contain: %s", content)
	}
}

func TestGoldenDeterministicOutput(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:  "deterministic-test",
		RunScript: "echo test",
	}

	// Execute the same template multiple times
	output1, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	output2, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	output3, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// All outputs should be identical
	assert.Equal(t, output1, output2, "template output should be deterministic")
	assert.Equal(t, output2, output3, "template output should be deterministic")
	assert.Equal(t, output1, output3, "template output should be deterministic")
}

func TestGoldenFullExample(t *testing.T) {
	// This test verifies a complete example combining header, helpers, steps, and commands
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	// Generate header
	headerData := HeaderData{
		SetName: "dev",
		Shell:   "bash",
	}
	header, err := tm.ExecuteHeader(headerData)
	assert.NoError(t, err)

	// Generate helpers
	helpers, err := tm.ExecuteHelper()
	assert.NoError(t, err)

	// Generate a step
	stepData := StepData{
		StepName:  "check-env",
		RunScript: "test -f .env",
	}
	step, err := tm.ExecuteStep(stepData)
	assert.NoError(t, err)

	// Generate a command
	cmdData := CommandData{
		CommandName: "init",
		MainRun:     "echo Initializing",
	}
	cmd, err := tm.ExecuteCommand(cmdData)
	assert.NoError(t, err)

	// Combine all parts
	fullOutput := header + "\n" + helpers + "\n" + step + "\n" + cmd

	// Verify the full output contains all expected sections
	assert.Contains(t, fullOutput, "# kfg shell integration", "full output should have header")
	assert.Contains(t, fullOutput, "__kfg_ctx_reset", "full output should have helpers")
	assert.Contains(t, fullOutput, "__kfg_run_step_check-env", "full output should have step")
	assert.Contains(t, fullOutput, "init()", "full output should have command")
}

// TestGoldenStepWithLogging validates that a Step using logging helpers
// generates correctly with the new helper names (__kfg_log_*).
// This test is part of task 4.3 from the replace-images-with-step-cache change.
func TestGoldenStepWithLogging(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:  "logging-step",
		RunScript: "__kfg_log_info \"step:logging\" \"Starting\"\necho \"Hello world\"\n__kfg_log_debug \"step:logging\" \"Completed\"",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Verify the helper function definitions are present
	
	

	// Verify the Step's run script is included (using the new helper names)
	assert.Contains(t, output, "__kfg_log_info \"step:logging\" \"Starting\"", "step should call __kfg_log_info")
	assert.Contains(t, output, "__kfg_log_debug \"step:logging\" \"Completed\"", "step should call __kfg_log_debug")
}

// TestGoldenStepWithCache validates that a Step with cache enabled
// generates cache check and store logic in the output.
// This test is part of task 5.2 from the replace-images-with-step-cache change.
func TestGoldenStepWithCache(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:    "cached-step",
		RunScript:   "echo hello world",
		CacheEnabled: true,
		HasOutput:    true,
		OutputName:   "result",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Verify cache check logic is present
	assert.Contains(t, output, "__kfg_cache_exists", "step should check if cache exists")

	// Verify cache restore logic is present
	assert.Contains(t, output, "__kfg_cache_restore", "step should restore from cache on hit")

	// Verify cache store logic is present
	assert.Contains(t, output, "__kfg_cache_store", "step should store to cache after execution")

	// Verify KFG_REFRESH check is present
	assert.Contains(t, output, "KFG_REFRESH", "step should check KFG_REFRESH environment variable")

}

// TestGoldenStepWithCacheDisabled validates that a Step without cache
// does not generate cache logic in the output.
// This test is part of task 5.2 from the replace-images-with-step-cache change.
func TestGoldenStepWithCacheDisabled(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:     "noncached-step",
		RunScript:    "echo hello world",
		CacheEnabled: false,
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Verify cache logic is NOT present when cache is disabled
	assert.NotContains(t, output, "__kfg_cache_exists", "step should NOT check cache when disabled")
	assert.NotContains(t, output, "__kfg_cache_restore", "step should NOT restore from cache when disabled")
	assert.NotContains(t, output, "__kfg_cache_store", "step should NOT store to cache when disabled")
}

// TestGoldenCacheOutputRestoration validates that when a Step with output
// is restored from cache, the output is set in __kfg_outputs for downstream use.
// This test is part of task 5.3 from the replace-images-with-step-cache change.
func TestGoldenCacheOutputRestoration(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	// Simulate a step like ctx7 install that has output
	data := StepData{
		StepName:     "ctx7-install",
		RunScript:    "ctx7 setup --cli --project $FLAGS",
		CacheEnabled: true,
		HasOutput:    true,
		OutputName:   "ctx7_context",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Verify output restoration is handled in cache restore
	// The generated code should pass the output name to __kfg_cache_restore
	assert.Contains(t, output, "__kfg_cache_restore", "cache restore should be called")
	assert.Contains(t, output, "ctx7_context", "output name should be passed to cache restore")
	
	// Verify the cache restore includes output restoration mechanism
	// __kfg_output_set is called inside __kfg_cache_restore when output is present
	// (This is validated by checking the helper template defines __kfg_output_set)
	helperOutput, err := tm.ExecuteHelper()
	assert.NoError(t, err)
	assert.Contains(t, helperOutput, "__kfg_output_set()", "helper should define __kfg_output_set for output restoration")
}

// TestGoldenStepWithOutputCleanupTrap validates that output-producing steps
// have trap-based cleanup for temporary output capture files.
// This test is part of task 2.1 from the fix-output-step-subshell-cache-loss change.
func TestGoldenStepWithOutputCleanupTrap(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:   "output-cleanup-step",
		HasOutput:  true,
		RunScript:  "echo 'test output'",
		OutputName: "result",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Verify trap-based cleanup is set up after creating temp file
	assert.Contains(t, output, "__output_file=$(mktemp)", "temp file should be created with mktemp")
	assert.Contains(t, output, "__cleanup_trap", "cleanup trap variable should be defined")
	assert.Contains(t, output, "rm -f", "cleanup trap should include rm command")
	assert.Contains(t, output, "trap", "trap should be set for cleanup")
	
	// Verify temp file cleanup happens on success path
	assert.Contains(t, output, "rm -f \"$__output_file\"", "temp file should be cleaned up explicitly on success")
	
	// Verify the output capture uses group command redirection (not subshell)
	assert.Contains(t, output, "{ echo 'test output'; } > \"$__output_file\"", 
		"output capture should use group command redirection to parent shell")
}

// TestGoldenStepWithOutputPreservesSideEffects validates that the generated
// output capture code runs in the parent shell (not a subshell), which
// preserves runtime side effects like __kfg_add_artifact calls.
// This test is part of task 2.1 from the fix-output-step-subshell-cache-loss change.
func TestGoldenStepWithOutputPreservesSideEffects(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	// This test verifies the STRUCTURE of the generated code,
	// not the runtime behavior (which is tested in Bats tests)
	data := StepData{
		StepName:   "artifact-output-step",
		HasOutput:  true,
		RunScript:  "echo 'result' && __kfg_add_artifact 'output.txt'",
		OutputName: "artifact_result",
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Verify the run script is included in a group command (runs in parent shell)
	assert.Contains(t, output, "{ echo 'result' && __kfg_add_artifact 'output.txt'; } > \"$__output_file\"",
		"run script should be in a group command that redirects to temp file")
	
	// Verify no command substitution is used for output capture
	assert.NotContains(t, output, "__output=\"$( ", 
		"should NOT use command substitution which runs in subshell")
}

// TestGoldenStepRefreshInvalidation validates that when KFG_REFRESH is set,
// the generated step wrapper invalidates (removes) the existing cache entry
// before execution and logs invalidation/rebuild semantics.
// This test is part of task 1.3 from the fix-refresh-step-cache-invalidation change.
func TestGoldenStepRefreshInvalidation(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	data := StepData{
		StepName:     "refresh-invalidation-step",
		RunScript:    "echo hello world",
		CacheEnabled: true,
	}

	output, err := tm.ExecuteStep(data)
	assert.NoError(t, err)

	// Verify refresh invalidation logic is present
	assert.Contains(t, output, "# Cache check (invalidate and rebuild when refresh is enabled)", 
		"step should have refresh invalidation comment")
	
	// Verify KFG_REFRESH check is present
	assert.Contains(t, output, "if [ -z \"${KFG_REFRESH:-}\" ]; then", 
		"step should check KFG_REFRESH")
	
	// Verify invalidation log when KFG_REFRESH is set
	assert.Contains(t, output, "__kfg_log_detail \"cache\" \"Invalidating cache for step", 
		"step should log invalidation when refresh is enabled")
	
	// Verify cache entry is removed when refresh is enabled
	assert.Contains(t, output, "rm -rf \"$__cache_path", 
		"step should remove cache entry when refresh is enabled")
	
	// Verify rebuild log is present in cache store section
	assert.Contains(t, output, "__kfg_log_detail \"cache\" \"Rebuilding cache for step", 
		"step should log rebuild when refresh is enabled")
	
	// Verify the invalidation is scoped to current step (not workflow-wide)
	// This is implicit in the __cache_path computation which is step-specific
	assert.Contains(t, output, "__kfg_cache_exists \"$__step_ref_name",
		"cache exists should use step ref name")
}

// TestGoldenCacheDelegation validates that cache helpers delegate to Go subcommands.
// This test verifies the new architecture where shell helpers are thin wrappers.
func TestGoldenCacheDelegation(t *testing.T) {
	tm, err := NewTemplateManager()
	assert.NoError(t, err)

	output, err := tm.ExecuteHelper()
	assert.NoError(t, err)

	// Verify __kfg_cache_exists delegates to kfg sys cache exists
	assert.Contains(t, output, "__kfg_internal sys cache exists",
		"cache exists should delegate to kfg sys cache exists")

	// Verify __kfg_cache_store delegates to kfg sys cache store
	assert.Contains(t, output, "__kfg_internal sys cache store",
		"cache store should delegate to kfg sys cache store")

	// Verify __kfg_cache_restore delegates to kfg sys cache restore
	assert.Contains(t, output, "__kfg_internal sys cache restore",
		"cache restore should delegate to kfg sys cache restore")

	// Verify __kfg_serialize_cache_input exists for JSON serialization
	assert.Contains(t, output, "__kfg_serialize_cache_input()",
		"helper should define __kfg_serialize_cache_input function")

	// Verify __kfg_internal helper exists
	assert.Contains(t, output, "__kfg_internal()",
		"helper should define __kfg_internal function")
}
