apiVersion: kfg.dev/v1alpha1
kind: Assets
metadata:
  name: ai.opencode.asset.settings
spec:
  input:
    format: yaml
  data:
    instructions:
      - AGENTS.md
    mode:
      plan:
        model: opencode/mimo-v2.5-free
      build:
        model: opencode/deepseek-v4-flash-free
