apiVersion: kfg.dev/v1alpha1
kind: Converter
metadata:
  name: kfg.convert.self.command.pi
spec:
  input:
    format: yaml
  engine:
    expression: |
      "---\nname: " + .name + "\ndescription: " + .description + "\n---\n\n" + .prompt
  output:
    format: raw
