apiVersion: kfg.dev/v1alpha1
kind: Step
metadata:
  name: kfg.convert
spec:
  run: |
    local asset="${ASSET:-}"
    local converter="${CONVERTER:-}"
    local output="${OUTPUT:-}"
    
    [ -z "$asset" ] && { _kfg.log.warn "no asset specified"; return 0; }
    [ -z "$converter" ] && { _kfg.log.warn "no converter specified"; return 0; }
    [ -z "$output" ] && { _kfg.log.warn "no output specified"; return 0; }
    
    local output_dir
    output_dir=$(dirname "$output")
    mkdir -p "$output_dir"

    kfg apply --convert "$asset" --use "$converter" -o "$output" -f "$KFG_BUILD_RESULT_FILE"
    
    __kfg_add_artifact "${output}"
    _kfg.log.info "converted '${asset}' -> ${output}"
  artifacts:
    - converted
  env:
    ASSET: ""
    CONVERTER: ""
    OUTPUT: ""
